using System;
using System.Collections.Generic;
using System.IO;
using FruitDefense.Tilemaps;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;

namespace FruitDefense.Editor
{
    public enum DualGridPixelWizardInputMode
    {
        Manual = 0,
        Imagegen = 1,
    }

    [Serializable]
    public sealed class DualGridPixelImagegenSourceRequest
    {
        public string role;
        public string targetAssetPath;
        public string prompt;
        public string[] requirements;
    }

    [Serializable]
    public sealed class DualGridPixelImagegenRequest
    {
        public int schemaVersion;
        public string terrainId;
        public string requiredSkill;
        public bool scriptDrawingAllowed;
        public string sourceLayout;
        public int nativeTileSize;
        public string instruction;
        public DualGridPixelImagegenSourceRequest[] sources;
    }

    public sealed class DualGridPixelTerrainWizard : EditorWindow
    {
        private const string DefaultTerrainId = "NewPixelTerrain";
        private const string DefaultTerrainParent = "Assets/DualGridTerrain";
        private static readonly string[] PixelRequirements =
        {
            "opaque RGB source with alpha 255 everywhere",
            "pixel-art material texture with crisp square pixel clusters",
            "no antialiasing, blur, gradients, text, logos, borders, or transparent pixels",
            "seamless repeating surface viewed straight-on without perspective",
            "source art must be generated by the imagegen skill, never by a drawing script",
        };

        [SerializeField] private DualGridPixelWizardInputMode inputMode =
            DualGridPixelWizardInputMode.Manual;
        [SerializeField] private DualGridPixelSourceLayout sourceLayout =
            DualGridPixelSourceLayout.GrassAndSoil;
        [SerializeField] private string terrainId = DefaultTerrainId;
        [SerializeField] private string assetRoot = DefaultTerrainParent + "/" + DefaultTerrainId;
        [SerializeField] private bool automaticAssetRoot = true;
        [SerializeField] private Texture2D grassTexture;
        [SerializeField] private Texture2D soilTexture;
        [SerializeField] private string grassPrompt =
            "lush readable green grass material for a cheerful defense game";
        [SerializeField] private string soilPrompt =
            "warm dark brown compact soil material matching the grass palette";
        [SerializeField] private int tileSize = 32;
        [SerializeField] private int outlinePixels;
        [SerializeField] private int soilRimPixels = 2;
        [SerializeField] private int textureGuidancePixels = 2;
        [SerializeField] private Color edgeColor = new Color32(65, 42, 27, 255);
        [SerializeField] private int deterministicSeed = 9137;
        [SerializeField] private DualGridPixelTerrainProfile activeProfile;
        [SerializeField] private Vector2 scrollPosition;

        [MenuItem("Fruit Defense/Dual Grid/Pixel Terrain Wizard")]
        public static void Open()
        {
            var window = GetWindow<DualGridPixelTerrainWizard>();
            window.titleContent = new GUIContent("Pixel Terrain");
            window.minSize = new Vector2(470f, 620f);
            window.Show();
        }

        private void OnGUI()
        {
            scrollPosition = EditorGUILayout.BeginScrollView(scrollPosition);
            DrawHeader();
            DrawIdentity();
            DrawSources();
            DrawRasterSettings();
            DrawOwnershipPreview();
            DrawPrimaryActions();
            DrawGeneratedActions();
            EditorGUILayout.EndScrollView();
        }

        private void DrawHeader()
        {
            EditorGUILayout.LabelField("Dual-Grid Pixel Terrain Wizard", EditorStyles.boldLabel);
            EditorGUILayout.HelpBox(
                "Manual mode references one or two existing opaque textures. AI mode creates an imagegen request and waits for Codex to save the generated PNGs; Unity never draws fallback source art.",
                MessageType.Info);
            EditorGUILayout.Space();
        }

        private void DrawIdentity()
        {
            EditorGUILayout.LabelField("1. Terrain ownership", EditorStyles.boldLabel);
            EditorGUI.BeginChangeCheck();
            terrainId = EditorGUILayout.TextField("Terrain Id", terrainId);
            var identityChanged = EditorGUI.EndChangeCheck();
            if (identityChanged && automaticAssetRoot)
                assetRoot = DefaultTerrainParent + "/" + terrainId.Trim();
            automaticAssetRoot = EditorGUILayout.Toggle("Automatic Asset Root", automaticAssetRoot);
            using (new EditorGUI.DisabledScope(automaticAssetRoot))
            {
                EditorGUI.BeginChangeCheck();
                assetRoot = EditorGUILayout.TextField("Asset Root", assetRoot);
                identityChanged |= EditorGUI.EndChangeCheck();
            }
            if (identityChanged) activeProfile = null;
            if (automaticAssetRoot)
                EditorGUILayout.LabelField("Asset Root", assetRoot, EditorStyles.wordWrappedLabel);
            inputMode = (DualGridPixelWizardInputMode)EditorGUILayout.EnumPopup(
                "Source Origin", inputMode);
            sourceLayout = (DualGridPixelSourceLayout)EditorGUILayout.EnumPopup(
                "Source Layout", sourceLayout);
            EditorGUILayout.Space();
        }

        private void DrawSources()
        {
            EditorGUILayout.LabelField("2. Source art", EditorStyles.boldLabel);
            if (inputMode == DualGridPixelWizardInputMode.Manual)
            {
                grassTexture = (Texture2D)EditorGUILayout.ObjectField(
                    sourceLayout == DualGridPixelSourceLayout.Single
                        ? "Surface Texture"
                        : "Grass Texture",
                    grassTexture, typeof(Texture2D), false);
                if (sourceLayout == DualGridPixelSourceLayout.GrassAndSoil)
                    soilTexture = (Texture2D)EditorGUILayout.ObjectField(
                        "Soil Texture", soilTexture, typeof(Texture2D), false);
                EditorGUILayout.HelpBox(
                    "Manual textures remain in their current asset paths. Bake configures Point import metadata but never copies or overwrites the image files.",
                    MessageType.None);
            }
            else
            {
                grassPrompt = EditorGUILayout.TextField(
                    sourceLayout == DualGridPixelSourceLayout.Single
                        ? "Surface Prompt"
                        : "Grass Prompt", grassPrompt);
                if (sourceLayout == DualGridPixelSourceLayout.GrassAndSoil)
                    soilPrompt = EditorGUILayout.TextField("Soil Prompt", soilPrompt);

                EditorGUILayout.LabelField("Expected imagegen outputs", EditorStyles.miniBoldLabel);
                EditorGUILayout.SelectableLabel(GetGrassTargetAssetPath(assetRoot, terrainId,
                    sourceLayout), EditorStyles.textField, GUILayout.Height(18f));
                if (sourceLayout == DualGridPixelSourceLayout.GrassAndSoil)
                    EditorGUILayout.SelectableLabel(GetSoilTargetAssetPath(assetRoot, terrainId),
                        EditorStyles.textField, GUILayout.Height(18f));

                EditorGUILayout.BeginHorizontal();
                if (GUILayout.Button("Prepare imagegen request")) PrepareImagegenRequest();
                if (GUILayout.Button("Refresh generated sources")) RefreshImagegenSources(true);
                EditorGUILayout.EndHorizontal();
                DrawImagegenSourceStatus();
            }
            EditorGUILayout.Space();
        }

        private void DrawRasterSettings()
        {
            EditorGUILayout.LabelField("3. Native pixel settings", EditorStyles.boldLabel);
            tileSize = EditorGUILayout.IntSlider("Tile Size", tileSize, 8, 128);
            if (tileSize % 2 != 0) tileSize++;
            outlinePixels = EditorGUILayout.IntSlider("Outline Pixels", outlinePixels, 0, 8);
            soilRimPixels = EditorGUILayout.IntSlider("Soil Rim Pixels", soilRimPixels, 1, 12);
            textureGuidancePixels = EditorGUILayout.IntSlider(
                "Texture Guidance Pixels", textureGuidancePixels, 0, 4);
            edgeColor = EditorGUILayout.ColorField("Edge Color", edgeColor);
            edgeColor.a = 1f;
            deterministicSeed = EditorGUILayout.IntField("Deterministic Seed", deterministicSeed);
            EditorGUILayout.Space();
        }

        private void DrawOwnershipPreview()
        {
            EditorGUILayout.LabelField("4. Owned outputs", EditorStyles.boldLabel);
            EditorGUILayout.LabelField("Profile", GetProfileAssetPath(assetRoot, terrainId));
            EditorGUILayout.LabelField("Generated", GetGeneratedFolder(assetRoot));
            EditorGUILayout.LabelField("TileSet", assetRoot + "/Generated/" + terrainId
                + "DualGridTileSet.asset");
            EditorGUILayout.LabelField("Atlas", "Builds/Evidence/"
                + DualGridPixelTileSetGenerator.ToEvidenceStem(terrainId)
                + "-dual-grid-16-mask-atlas.png");
            EditorGUILayout.Space();
        }

        private void DrawPrimaryActions()
        {
            var canBake = TryResolveSources(out var grass, out var soil, out var reason)
                && ValidateWizardSettings(out reason);
            if (!canBake) EditorGUILayout.HelpBox(reason, MessageType.Warning);
            using (new EditorGUI.DisabledScope(!canBake))
            {
                if (GUILayout.Button("Create or Update Profile + Bake", GUILayout.Height(34f)))
                {
                    var origin = inputMode == DualGridPixelWizardInputMode.Imagegen
                        ? DualGridPixelSourceOrigin.Imagegen
                        : DualGridPixelSourceOrigin.Manual;
                    activeProfile = CreateOrUpdateProfile(assetRoot, terrainId, origin,
                        sourceLayout, grass, soil, tileSize, outlinePixels, soilRimPixels,
                        textureGuidancePixels, (Color32)edgeColor, deterministicSeed, true);
                    ShowNotification(new GUIContent("Pixel terrain baked and validated"));
                }
            }
            EditorGUILayout.Space();
        }

        private void DrawGeneratedActions()
        {
            RefreshProfileReference();
            if (activeProfile == null) return;
            EditorGUILayout.LabelField("Generated profile", EditorStyles.boldLabel);
            activeProfile = (DualGridPixelTerrainProfile)EditorGUILayout.ObjectField(
                activeProfile, typeof(DualGridPixelTerrainProfile), false);
            EditorGUILayout.BeginHorizontal();
            if (GUILayout.Button("Validate"))
            {
                DualGridPixelTileSetGenerator.ValidateGeneratedPixelTileSet(activeProfile);
                ShowNotification(new GUIContent("Validation passed"));
            }
            if (GUILayout.Button("Reveal Output")) RevealOutput(activeProfile);
            EditorGUILayout.EndHorizontal();

            var selectedMap = FindSelectedMap();
            using (new EditorGUI.DisabledScope(selectedMap == null))
            {
                if (GUILayout.Button(selectedMap == null
                        ? "Select a DualGridTilemap to apply"
                        : "Apply TileSet to Selected DualGridTilemap"))
                {
                    if (!ApplyToMap(activeProfile, selectedMap, out var reason))
                        throw new InvalidOperationException(reason);
                    ShowNotification(new GUIContent("TileSet applied and map rebuilt"));
                }
            }
        }

        private void PrepareImagegenRequest()
        {
            if (!ValidateWizardSettings(out var reason))
                throw new InvalidOperationException(reason);
            if (string.IsNullOrWhiteSpace(grassPrompt)
                || (sourceLayout == DualGridPixelSourceLayout.GrassAndSoil
                    && string.IsNullOrWhiteSpace(soilPrompt)))
                throw new InvalidOperationException("Every requested imagegen source needs a prompt.");

            var requestPath = WriteImagegenRequest(assetRoot, terrainId, sourceLayout,
                tileSize, grassPrompt, soilPrompt);
            EditorGUIUtility.systemCopyBuffer = BuildCodexImagegenInstruction(requestPath);
            AssetDatabase.Refresh(ImportAssetOptions.ForceSynchronousImport);
            Selection.activeObject = AssetDatabase.LoadAssetAtPath<UnityEngine.Object>(requestPath);
            ShowNotification(new GUIContent("Request saved; Codex instruction copied"));
        }

        private void RefreshImagegenSources(bool notify)
        {
            if (notify) AssetDatabase.Refresh(ImportAssetOptions.ForceSynchronousImport);
            grassTexture = AssetDatabase.LoadAssetAtPath<Texture2D>(
                GetGrassTargetAssetPath(assetRoot, terrainId, sourceLayout));
            soilTexture = sourceLayout == DualGridPixelSourceLayout.Single
                ? null
                : AssetDatabase.LoadAssetAtPath<Texture2D>(
                    GetSoilTargetAssetPath(assetRoot, terrainId));
            if (notify)
                ShowNotification(new GUIContent(grassTexture != null
                    && (sourceLayout == DualGridPixelSourceLayout.Single || soilTexture != null)
                        ? "Imagegen sources found"
                        : "Waiting for imagegen source PNGs"));
        }

        private void DrawImagegenSourceStatus()
        {
            RefreshImagegenSources(false);
            var missing = new List<string>();
            if (grassTexture == null)
                missing.Add(GetGrassTargetAssetPath(assetRoot, terrainId, sourceLayout));
            if (sourceLayout == DualGridPixelSourceLayout.GrassAndSoil && soilTexture == null)
                missing.Add(GetSoilTargetAssetPath(assetRoot, terrainId));
            if (missing.Count == 0)
                EditorGUILayout.HelpBox("All imagegen source PNGs are imported.", MessageType.Info);
            else
                EditorGUILayout.HelpBox("Waiting for imagegen. Missing:\n" + string.Join("\n", missing),
                    MessageType.Warning);
        }

        private bool TryResolveSources(out Texture2D grass, out Texture2D soil,
            out string reason)
        {
            grass = grassTexture;
            soil = sourceLayout == DualGridPixelSourceLayout.Single ? null : soilTexture;
            if (grass == null)
            {
                reason = inputMode == DualGridPixelWizardInputMode.Imagegen
                    ? "The required imagegen surface PNG has not arrived yet."
                    : "Select a surface or grass texture.";
                return false;
            }
            if (sourceLayout == DualGridPixelSourceLayout.GrassAndSoil && soil == null)
            {
                reason = inputMode == DualGridPixelWizardInputMode.Imagegen
                    ? "The required imagegen soil PNG has not arrived yet."
                    : "Select a soil texture.";
                return false;
            }
            reason = "ok";
            return true;
        }

        private bool ValidateWizardSettings(out string reason)
        {
            return ValidateWizardSettings(assetRoot, terrainId, tileSize, outlinePixels,
                soilRimPixels, textureGuidancePixels, out reason);
        }

        public static bool ValidateWizardSettings(string root, string id, int nativeTileSize,
            int outlineWidth, int soilRimWidth, out string reason)
        {
            return ValidateWizardSettings(root, id, nativeTileSize, outlineWidth,
                soilRimWidth, 2, out reason);
        }

        public static bool ValidateWizardSettings(string root, string id, int nativeTileSize,
            int outlineWidth, int soilRimWidth, int guidanceWidth, out string reason)
        {
            if (string.IsNullOrWhiteSpace(id)
                || id.IndexOfAny(Path.GetInvalidFileNameChars()) >= 0
                || id.Contains("/") || id.Contains("\\"))
            {
                reason = "Terrain Id must be a valid filename stem.";
                return false;
            }
            var normalizedRoot = NormalizeAssetPath(root);
            if (string.IsNullOrWhiteSpace(normalizedRoot)
                || !normalizedRoot.StartsWith("Assets/", StringComparison.Ordinal)
                || normalizedRoot.Contains(".."))
            {
                reason = "Asset Root must stay under Assets/ and cannot contain '..'.";
                return false;
            }
            if (nativeTileSize < 8 || nativeTileSize % 2 != 0)
            {
                reason = "Tile Size must be even and at least 8.";
                return false;
            }
            if (outlineWidth < 0 || soilRimWidth < 1
                || outlineWidth + soilRimWidth + 1 >= nativeTileSize / 2)
            {
                reason = "Outline and soil rim must leave an interior pixel region.";
                return false;
            }
            if (guidanceWidth < 0 || guidanceWidth > 4)
            {
                reason = "Texture Guidance Pixels must be between 0 and 4.";
                return false;
            }
            reason = "ok";
            return true;
        }

        public static DualGridPixelTerrainProfile CreateOrUpdateProfile(string root,
            string id, DualGridPixelSourceOrigin origin, DualGridPixelSourceLayout layout,
            Texture2D grass, Texture2D soil, int nativeTileSize, int outlineWidth,
            int soilRimWidth, Color32 outlineColor, int seed, bool bake)
        {
            return CreateOrUpdateProfile(root, id, origin, layout, grass, soil, nativeTileSize,
                outlineWidth, soilRimWidth, 2, outlineColor, seed, bake);
        }

        public static DualGridPixelTerrainProfile CreateOrUpdateProfile(string root,
            string id, DualGridPixelSourceOrigin origin, DualGridPixelSourceLayout layout,
            Texture2D grass, Texture2D soil, int nativeTileSize, int outlineWidth,
            int soilRimWidth, int guidanceWidth, Color32 outlineColor, int seed, bool bake)
        {
            if (!ValidateWizardSettings(root, id, nativeTileSize, outlineWidth,
                    soilRimWidth, guidanceWidth, out var reason))
                throw new InvalidOperationException(reason);
            if (grass == null) throw new ArgumentNullException(nameof(grass));
            if (layout == DualGridPixelSourceLayout.GrassAndSoil && soil == null)
                throw new ArgumentNullException(nameof(soil));

            var normalizedRoot = NormalizeAssetPath(root);
            EnsureAssetFolder(normalizedRoot);
            EnsureAssetFolder(GetGeneratedFolder(normalizedRoot));
            EnsureUniqueOwnership(normalizedRoot, id);
            var profilePath = GetProfileAssetPath(normalizedRoot, id);
            var profile = AssetDatabase.LoadAssetAtPath<DualGridPixelTerrainProfile>(profilePath);
            if (profile == null)
            {
                profile = CreateInstance<DualGridPixelTerrainProfile>();
                AssetDatabase.CreateAsset(profile, profilePath);
            }
            else
            {
                Undo.RecordObject(profile, "Update Dual-Grid pixel terrain profile");
            }
            profile.Configure(origin, layout, grass, soil, id, GetGeneratedFolder(normalizedRoot),
                nativeTileSize, outlineWidth, soilRimWidth, outlineColor, seed, guidanceWidth);
            EditorUtility.SetDirty(profile);
            AssetDatabase.SaveAssets();
            if (bake) DualGridPixelTileSetGenerator.Bake(profile);
            return profile;
        }

        public static string WriteImagegenRequest(string root, string id,
            DualGridPixelSourceLayout layout, int nativeTileSize, string surfacePrompt,
            string requestedSoilPrompt)
        {
            var normalizedRoot = NormalizeAssetPath(root);
            EnsureAssetFolder(normalizedRoot);
            var sourceFolder = normalizedRoot + "/Sources";
            EnsureAssetFolder(sourceFolder);
            var request = CreateImagegenRequest(normalizedRoot, id, layout, nativeTileSize,
                surfacePrompt, requestedSoilPrompt);
            var requestPath = GetImagegenRequestAssetPath(normalizedRoot, id);
            var projectRoot = Directory.GetParent(Application.dataPath).FullName;
            var absolutePath = Path.GetFullPath(Path.Combine(projectRoot,
                requestPath.Replace('/', Path.DirectorySeparatorChar)));
            Directory.CreateDirectory(Path.GetDirectoryName(absolutePath));
            File.WriteAllText(absolutePath, JsonUtility.ToJson(request, true));
            return requestPath;
        }

        public static DualGridPixelImagegenRequest CreateImagegenRequest(string root, string id,
            DualGridPixelSourceLayout layout, int nativeTileSize, string surfacePrompt,
            string requestedSoilPrompt)
        {
            var normalizedRoot = NormalizeAssetPath(root);
            var requests = new List<DualGridPixelImagegenSourceRequest>
            {
                NewSourceRequest(layout == DualGridPixelSourceLayout.Single ? "surface" : "grass",
                    GetGrassTargetAssetPath(normalizedRoot, id, layout), surfacePrompt),
            };
            if (layout == DualGridPixelSourceLayout.GrassAndSoil)
                requests.Add(NewSourceRequest("soil", GetSoilTargetAssetPath(normalizedRoot, id),
                    requestedSoilPrompt));

            return new DualGridPixelImagegenRequest
            {
                schemaVersion = 1,
                terrainId = id,
                requiredSkill = "imagegen",
                scriptDrawingAllowed = false,
                sourceLayout = layout.ToString(),
                nativeTileSize = nativeTileSize,
                instruction = "Generate every listed bitmap with the imagegen skill and save it at the exact targetAssetPath. Never use a script, canvas, shader, or procedural fallback to draw source art.",
                sources = requests.ToArray(),
            };
        }

        public static string GetImagegenRequestAssetPath(string root, string id)
        {
            return NormalizeAssetPath(root) + "/Sources/" + id + "-imagegen-request.json";
        }

        public static string BuildCodexImagegenInstruction(string requestAssetPath)
        {
            return "请读取并执行 Unity 像素地形生图请求：" + requestAssetPath
                + "。必须使用 imagegen 生图技能生成其中每一张源图，并保存到 JSON 指定的 targetAssetPath；严禁使用脚本、Canvas、Shader 或程序化方式自行绘制源图。完成后不要运行其他图片生成方式。";
        }

        public static string GetProfileAssetPath(string root, string id)
        {
            return NormalizeAssetPath(root) + "/" + id + "BakeProfile.asset";
        }

        public static string GetGeneratedFolder(string root)
        {
            return NormalizeAssetPath(root) + "/Generated";
        }

        public static string GetGrassTargetAssetPath(string root, string id,
            DualGridPixelSourceLayout layout)
        {
            return NormalizeAssetPath(root) + "/Sources/" + id
                + (layout == DualGridPixelSourceLayout.Single ? "-Source.png" : "-Grass.png");
        }

        public static string GetSoilTargetAssetPath(string root, string id)
        {
            return NormalizeAssetPath(root) + "/Sources/" + id + "-Soil.png";
        }

        public static bool ApplyToMap(DualGridPixelTerrainProfile profile, DualGridTilemap map,
            out string reason)
        {
            if (profile == null)
            {
                reason = "A generated pixel terrain profile is required.";
                return false;
            }
            if (map == null)
            {
                reason = "Select a GameObject with DualGridTilemap.";
                return false;
            }
            if (map.LogicalTilemap == null || map.GeneratedTilemap == null)
            {
                reason = "The selected DualGridTilemap needs logical and generated Tilemaps.";
                return false;
            }
            var tileSetPath = DualGridPixelTileSetGenerator.GetTileSetAssetPath(profile);
            var tileSet = AssetDatabase.LoadAssetAtPath<DualGridTileSet>(tileSetPath);
            if (tileSet == null)
            {
                reason = "Bake the profile before applying it: " + tileSetPath;
                return false;
            }

            Undo.RecordObject(map, "Apply pixel Dual-Grid TileSet");
            Undo.RecordObject(map.GeneratedTilemap.transform, "Align pixel Dual-Grid output");
            Undo.RegisterCompleteObjectUndo(map.GeneratedTilemap, "Rebuild pixel Dual-Grid output");
            map.Configure(map.LogicalTilemap, map.GeneratedTilemap, tileSet,
                map.AutomaticRefresh);
            if (!map.AlignGeneratedTilemap())
            {
                reason = "Could not align the selected generated Tilemap.";
                return false;
            }
            if (!map.Rebuild(out reason)) return false;
            EditorUtility.SetDirty(map);
            EditorUtility.SetDirty(map.GeneratedTilemap);
            if (map.gameObject.scene.IsValid()) EditorSceneManager.MarkSceneDirty(map.gameObject.scene);
            reason = "ok";
            return true;
        }

        private static DualGridPixelImagegenSourceRequest NewSourceRequest(string role,
            string targetAssetPath, string prompt)
        {
            return new DualGridPixelImagegenSourceRequest
            {
                role = role,
                targetAssetPath = targetAssetPath,
                prompt = prompt,
                requirements = (string[])PixelRequirements.Clone(),
            };
        }

        private static void EnsureUniqueOwnership(string root, string id)
        {
            var candidateProfilePath = GetProfileAssetPath(root, id);
            var candidateEvidence = "Builds/Evidence/"
                + DualGridPixelTileSetGenerator.ToEvidenceStem(id)
                + "-dual-grid-validation.json";
            foreach (var guid in AssetDatabase.FindAssets("t:DualGridPixelTerrainProfile"))
            {
                var path = AssetDatabase.GUIDToAssetPath(guid);
                if (string.Equals(path, candidateProfilePath, StringComparison.OrdinalIgnoreCase))
                    continue;
                var existing = AssetDatabase.LoadAssetAtPath<DualGridPixelTerrainProfile>(path);
                if (existing == null) continue;
                if (string.Equals(existing.TerrainId, id, StringComparison.OrdinalIgnoreCase)
                    || string.Equals(DualGridPixelTileSetGenerator.GetValidationEvidencePath(existing),
                        candidateEvidence, StringComparison.OrdinalIgnoreCase))
                    throw new InvalidOperationException("Terrain Id/evidence ownership conflicts with "
                        + path + ". Choose another Terrain Id.");
            }
        }

        private static void RevealOutput(DualGridPixelTerrainProfile profile)
        {
            var output = AssetDatabase.LoadAssetAtPath<UnityEngine.Object>(profile.OutputFolder);
            if (output == null) throw new InvalidOperationException(
                "Generated output folder is missing: " + profile.OutputFolder);
            Selection.activeObject = output;
            EditorGUIUtility.PingObject(output);
        }

        private static DualGridTilemap FindSelectedMap()
        {
            if (Selection.activeGameObject == null) return null;
            var direct = Selection.activeGameObject.GetComponent<DualGridTilemap>();
            return direct != null
                ? direct
                : Selection.activeGameObject.GetComponentInParent<DualGridTilemap>();
        }

        private void RefreshProfileReference()
        {
            if (activeProfile != null) return;
            if (!ValidateWizardSettings(out _)) return;
            activeProfile = AssetDatabase.LoadAssetAtPath<DualGridPixelTerrainProfile>(
                GetProfileAssetPath(assetRoot, terrainId));
        }

        private static string NormalizeAssetPath(string path)
        {
            return string.IsNullOrWhiteSpace(path)
                ? string.Empty
                : path.Replace('\\', '/').Trim().TrimEnd('/');
        }

        private static void EnsureAssetFolder(string assetFolder)
        {
            var normalized = NormalizeAssetPath(assetFolder);
            if (AssetDatabase.IsValidFolder(normalized)) return;
            var parent = Path.GetDirectoryName(normalized);
            if (string.IsNullOrWhiteSpace(parent))
                throw new InvalidOperationException("Invalid asset folder: " + assetFolder);
            parent = NormalizeAssetPath(parent);
            if (!AssetDatabase.IsValidFolder(parent)) EnsureAssetFolder(parent);
            AssetDatabase.CreateFolder(parent, Path.GetFileName(normalized));
        }
    }
}
